# Generated by Django 5.1.4 on 2026-03-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_match_current_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('history', 'History'), ('black_culture', 'Black Culture'), ('hip_hop', 'Hip-Hop & Music'), ('sports', 'Sports'), ('film_tv', 'Film & TV'), ('science', 'Science & Innovation'), ('food_culture', 'Food & Culture'), ('literature', 'Literature & Art'), ('current_events', 'Current Events')], max_length=50),
        ),
    ]
