# Generated by Django 5.1.4 on 2026-03-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_blackcard_match_card_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='question_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
