# Generated by Django 5.2.12 on 2026-03-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_match_question_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="categories",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
